/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./resources/js/components/Ui/Button.vue')['default']
    Input: typeof import('./resources/js/components/Ui/Input.vue')['default']
    LanguageSwitcher: typeof import('./resources/js/components/shared/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./resources/js/components/ui/UiButton.vue')['default']
    UiInput: typeof import('./resources/js/components/ui/UiInput.vue')['default']
    UiToast: typeof import('./resources/js/components/ui/UiToast.vue')['default']
  }
}
